import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <div className="app">
          <TopNav />
          {children}
        </div>
      </body>
    </html>
  );
}

function TopNav() {
  return (
    <nav className="flex w-full items-center justify-between p-3 text-lg font-medium">
      <div>Image Gallery</div>
      <div>Sign In</div>
    </nav>
  );
}
